[tool.poetry]
name = "worker"
version = "0.1.0"
description = ""
authors = []

packages = [{ include = "src", from = "." }]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
